### ISSUE TITLE
Investigate better base case sorters

### ISSUE THREAD

**Issue by lorenzhs** [lorenzhs/ssssort#4]
Something from Martin Aumüller's exhaustive investigation of quicksort variants (including multi-pivot) maybe? http://eiche.theoinf.tu-ilmenau.de/quicksort-experiments/ (they're GPL though)

**Comment by Morwenn** [comment]
You might want to have a look at [pattern-defeating quicksort](https://github.com/orlp/pdqsort), which uses a new partitioning scheme and a few pattern-breaking schemes that happen to work pretty well on real-world data.

It's zlib licensed if that matters.

**Comment by lorenzhs** [comment]
Thanks, that looks interesting - I'll have a look

**Comment by lorenzhs** [comment]
It's about the same as `std::sort` in most benchmarks, but significantly faster in the last three. Nice! I'll have to look into license compatibility but it looks like it shouldn't be a problem.

**Comment by Morwenn** [comment]
Actually, there [a new branch][1] on pdqsort using a partition function less affected by cache misses. The algorithm is now twice as fast as `std::sort` on average.

  [1]: https://github.com/orlp/pdqsort/tree/block

**Comment by lorenzhs** [comment]
Oh cool it implements blocked quicksort now? I tried that as a base case before (didn't push, the paper authors' [implementation](https://github.com/weissan/BlockQuicksort) is GPLv3), and it definitely makes ssssort faster. On its own its speed is comparable to ssssort (sometimes faster, sometimes not) but without the memory overhead. See https://arxiv.org/abs/1604.06697, they compare to my implementation.

BlockQS is definitely very interesting.

**Comment by Morwenn** [comment]
Yep, it uses ideas from BlockQuicksort's partition, but still uses its own original tweaks to avoid bad partitions as much as possible.

**Comment by lorenzhs** [comment]
The [pdq branch](https://github.com/lorenzhs/ssssort/tree/pdq) has this covered now
